version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /home/sungjin/capstone/tmp:/videos  # Change to your own path
    environment:
      - UPLOAD_DIR=/videos
      - TRITON_URL=http://localhost:8000/v2/models/ensemble/infer


